package com.example.ui.theme

object AppStrings {
    private val en = mapOf(
        "app_title" to "Quran Sunao",
        "app_tagline" to "Your daily Qur'an, kept simple!",
        "dashboard" to "Dashboard",
        "students" to "Students",
        "attendance" to "Attendance",
        "students_and_attendance" to "Students & Attendance",
        "chat" to "Chat",
        "quran" to "Qur'an",
        "profile" to "Profile",
        "settings" to "Settings",
        "login" to "Login",
        "signup" to "Sign Up",
        "email" to "Email Address",
        "password" to "Password",
        "continue_email" to "Continue with Email",
        "continue_google" to "Continue with Google",
        "forgot_password" to "Forgot Password?",
        "role_teacher" to "Teacher View",
        "role_student" to "Student View",
        "switch_to_teacher" to "Switch to Teacher",
        "switch_to_student" to "Switch to Student",
        "total_students" to "Total Students",
        "today_attendance" to "Today's Attendance",
        "pending_sessions" to "Pending Sabaq",
        "start_session" to "Start Listening",
        "start_call" to "Video Call",
        "send_message" to "Send Message",
        "current_sabaq" to "Current Sabaq",
        "para" to "Para",
        "surah" to "Surah",
        "ayah" to "Ayah",
        "listen_session_title" to "Listening Session",
        "correct" to "Correct",
        "mistake" to "Mistake",
        "needs_practice" to "Needs Practice",
        "teacher_remarks" to "Teacher Remarks & Tajweed Notes",
        "complete_session" to "Complete Session",
        "advance_pointer" to "Advance Lesson Pointer Automatically",
        "present" to "Present",
        "absent" to "Absent",
        "leave" to "Leave",
        "attendance_rate" to "Attendance Rate",
        "monthly_attendance" to "Monthly Attendance",
        "export_csv" to "Export CSV Report",
        "all_surahs" to "Surahs",
        "all_paras" to "Paras (Juz)",
        "bookmarks" to "Bookmarks",
        "search_surah" to "Search Surah or Para...",
        "arabic_only" to "Arabic",
        "with_english" to "+ English",
        "with_urdu" to "+ Urdu",
        "all_translations" to "All",
        "play_recitation" to "Play Recitation",
        "pause" to "Pause",
        "about_teacher" to "About Teacher & Qualifications",
        "contact_teacher" to "Contact Teacher",
        "whatsapp_1" to "Chat on WhatsApp (Direct)",
        "whatsapp_2" to "Parent Helpline (WhatsApp)",
        "daily_reminder" to "Daily Sabaq Reminder",
        "reminder_time" to "Reminder Scheduled for",
        "language_toggle" to "Language (English / اردو)",
        "dark_mode" to "Dark Mode",
        "privacy_policy" to "Privacy Policy",
        "terms_of_use" to "Terms of Use",
        "logout" to "Log Out",
        "add_student" to "Add New Student",
        "student_name" to "Student Full Name",
        "phone_number" to "Phone Number",
        "parent_contact" to "Parent Contact Info",
        "save_student" to "Enroll Student",
        "cancel" to "Cancel",
        "type_message" to "Type a message or recitation note...",
        "incoming_call" to "Incoming Qur'an Call",
        "join_call" to "Join Call",
        "dismiss" to "Dismiss",
        "end_call" to "End Call",
        "camera" to "Camera",
        "mic" to "Mute",
        "speaker" to "Speaker",
        "generate_meet_link" to "Google Meet Link",
        "generate_zoom_link" to "Zoom Link",
        "native_call" to "Native In-App Call",
        "call_history" to "Recent Calls Log",
        "quran_progress" to "Qur'an Completion Progress",
        "continue_where_left" to "Continue Where You Left Off",
        "next_lesson_in" to "Next Sabaq Session",
        "lesson_pointer" to "Current Pointer",
        "joined_date" to "Enrolled On",
        "change_password" to "Change Password",
        "save_changes" to "Save Changes",
        "bio" to "Teacher Bio & Experience",
        "qualifications" to "Certifications & Ijazah",
        "offline_cached" to "Offline Ready & Cached",
        "notifications" to "Notifications",
        "save_to_google" to "Save Password to Google",
        "google_password_manager" to "Google Password Manager",
        "google_save_subtitle" to "Google Password Manager secures credentials across all your devices",
        "lively_feed" to "Live Activity & Notifications",
        "mark_all_read" to "Mark All Read",
        "daily_ayah" to "Ayah of the Day",
        "hadith_quote" to "Daily Motivation",
        "bismillah_start" to "Bismillah • Start",
        "chats" to "Chats",
        "status" to "Status",
        "calls" to "Calls",
        "search_messages" to "Search chats or students...",
        "online" to "online",
        "last_seen_today" to "last seen today at",
        "today" to "Today",
        "yesterday" to "Yesterday",
        "new_chat" to "New Chat",
        "select_contact" to "Select Contact",
        "my_status" to "My Status",
        "tap_add_status" to "Tap to add recitation status",
        "recent_updates" to "Recent Updates",
        "no_chats_yet" to "No chats yet",
        "start_chat_hint" to "Tap the button below to start a conversation",
        "view_contact" to "View Contact Details",
        "clear_chat" to "Clear Messages",
        "voice_message_hint" to "Hold to record Sabaq voice note",
        "voice_note_sent" to "🎤 Sabaq Voice Note (0:45)",
        "attach_sabaq" to "Share Sabaq Pointer",
        "attach_verse" to "Share Ayah from Quran",
        "call_back" to "Call Back"
    )

    private val ur = mapOf(
        "app_title" to "قرآن سناؤ",
        "app_tagline" to "آپ کا روزانہ قرآن، آسان اور پرسکون!",
        "dashboard" to "ڈیش بورڈ",
        "students" to "طلباء",
        "attendance" to "حاضری",
        "students_and_attendance" to "طلباء اور حاضری",
        "chat" to "پیغامات",
        "quran" to "قرآن مجید",
        "profile" to "پروفائل",
        "settings" to "سیٹنگز",
        "login" to "لاگ ان کریں",
        "signup" to "نیا اکاؤنٹ بنائیں",
        "email" to "ای میل پتہ",
        "password" to "پاس ورڈ",
        "continue_email" to "ای میل کے ساتھ لاگ ان",
        "continue_google" to "گوگل سے لاگ ان",
        "forgot_password" to "پاس ورڈ بھول گئے؟",
        "role_teacher" to "معلمہ پورٹل",
        "role_student" to "طالب علم پورٹل",
        "switch_to_teacher" to "معلمہ پورٹل پر جائیں",
        "switch_to_student" to "طالب علم پورٹل پر جائیں",
        "total_students" to "کل طلباء",
        "today_attendance" to "آج کی حاضری",
        "pending_sessions" to "باقی اسباق",
        "start_session" to "سبق سنیں",
        "start_call" to "ویڈیو کال",
        "send_message" to "پیغام بھیجیں",
        "current_sabaq" to "موجودہ سبق",
        "para" to "پارہ",
        "surah" to "سورۃ",
        "ayah" to "آیت",
        "listen_session_title" to "سبق سماعت کا سیشن",
        "correct" to "صحیح",
        "mistake" to "غلطی",
        "needs_practice" to "مشق درکار",
        "teacher_remarks" to "معلمہ کے تجوید نوٹس اور ہدایات",
        "complete_session" to "سیشن مکمل کریں",
        "advance_pointer" to "خودکار طور پر اگلا سبق لگائیں",
        "present" to "حاضر",
        "absent" to "غیر حاضر",
        "leave" to "رخصت",
        "attendance_rate" to "حاضری کا تناسب",
        "monthly_attendance" to "ماہانہ حاضری ریکارڈ",
        "export_csv" to "ایکسپورٹ CSV رپورٹ",
        "all_surahs" to "سورتیں",
        "all_paras" to "پارے",
        "bookmarks" to "بک مارکس",
        "search_surah" to "سورۃ یا پارہ تلاش کریں...",
        "arabic_only" to "صرف عربی",
        "with_english" to "+ انگریزی",
        "with_urdu" to "+ اردو",
        "all_translations" to "تمام",
        "play_recitation" to "تلاوت سنیں",
        "pause" to "روکیں",
        "about_teacher" to "معلمہ کا تعارف و اسناد",
        "contact_teacher" to "معلمہ سے رابطہ",
        "whatsapp_1" to "واٹس ایپ چیٹ (براہِ راست)",
        "whatsapp_2" to "والدین ہیلپ لائن (واٹس ایپ)",
        "daily_reminder" to "روزانہ سبق کی یاد دہانی",
        "reminder_time" to "یاد دہانی کا وقت",
        "language_toggle" to "زبان (English / اردو)",
        "dark_mode" to "ڈارک موڈ",
        "privacy_policy" to "پرائیویسی پالیسی",
        "terms_of_use" to "شرائط و ضوابط",
        "logout" to "لاگ آؤٹ",
        "add_student" to "نیا طالب علم شامل کریں",
        "student_name" to "طالب علم کا پورا نام",
        "phone_number" to "فون نمبر",
        "parent_contact" to "والدین کا رابطہ",
        "save_student" to "طالب علم محفوظ کریں",
        "cancel" to "منسوخ",
        "type_message" to "پیغام یا سبق سے متعلق تحریر کریں...",
        "incoming_call" to "قرآن سنانے کی کال آ رہی ہے",
        "join_call" to "کال قبول کریں",
        "dismiss" to "مسترد",
        "end_call" to "کال ختم کریں",
        "camera" to "کیمرہ",
        "mic" to "مائیک",
        "speaker" to "اسپیکر",
        "generate_meet_link" to "گوگل میٹ لنک",
        "generate_zoom_link" to "زوم لنک",
        "native_call" to "براہِ راست ایپ کال",
        "call_history" to "حالیہ کالز لاگ",
        "quran_progress" to "قرآن مکمل کرنے کی پیشرفت",
        "continue_where_left" to "جہاں سے چھوڑا تھا وہیں سے پڑھیں",
        "next_lesson_in" to "اگلا سبق کا وقت",
        "lesson_pointer" to "موجودہ سبق",
        "joined_date" to "داخلہ کی تاریخ",
        "change_password" to "پاس ورڈ تبدیل کریں",
        "save_changes" to "تبدیلیاں محفوظ کریں",
        "bio" to "معلمہ کا تجربہ اور تفصیل",
        "qualifications" to "اسناد اور اجازہ",
        "offline_cached" to "آف لائن کیش محفوظ ہے",
        "notifications" to "اطلاعات اور نوٹس",
        "save_to_google" to "پاس ورڈ گوگل میں محفوظ کریں",
        "google_password_manager" to "گوگل پاس ورڈ مینیجر",
        "google_save_subtitle" to "گوگل پاس ورڈ مینیجر آپ کا لاگ ان ہر ڈیوائس پر محفوظ رکھے گا",
        "lively_feed" to "تازہ ترین سرگرمیاں اور اطلاعات",
        "mark_all_read" to "سب پڑھا ہوا کریں",
        "daily_ayah" to "آج کی منتخب آیت",
        "hadith_quote" to "روزانہ حدیث و ترغیب",
        "bismillah_start" to "بسم اللہ • شروع کریں",
        "chats" to "چیٹس",
        "status" to "اسٹیٹس",
        "calls" to "کالز",
        "search_messages" to "پیغامات یا طلباء تلاش کریں...",
        "online" to "آن لائن",
        "last_seen_today" to "آخری بار دیکھا گیا آج",
        "today" to "آج",
        "yesterday" to "کل",
        "new_chat" to "نئی گفتگو",
        "select_contact" to "رابطہ منتخب کریں",
        "my_status" to "میرا اسٹیٹس",
        "tap_add_status" to "تلاوت یا سبق کا اسٹیٹس لگائیں",
        "recent_updates" to "حالیہ اپ ڈیٹس",
        "no_chats_yet" to "کوئی گفتگو موجود نہیں",
        "start_chat_hint" to "گفتگو شروع کرنے کے لیے نیچے بٹن دبائیں",
        "view_contact" to "رابطہ کی تفصیلات",
        "clear_chat" to "پیغامات صاف کریں",
        "voice_message_hint" to "سبق کی آڈیو ریکارڈ کرنے کے لیے دبائے رکھیں",
        "voice_note_sent" to "🎤 سبق کی آڈیو ریکارڈنگ (0:45)",
        "attach_sabaq" to "موجودہ سبق کا حوالہ بھیجیں",
        "attach_verse" to "قرآن سے آیت منتخب کریں",
        "call_back" to "دوبارہ کال کریں"
    )

    fun get(key: String, lang: String = "en"): String {
        val dict = if (lang == "ur") ur else en
        return dict[key] ?: en[key] ?: key
    }
}
